- name: Crear base de datos usando psql
  become: true
  shell: |
    sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = '{{ item.name }}'" | grep -q 1 || \
    sudo -u postgres createdb {{ item.name }}
  loop: "{{ postgresql_databases }}"
