- name: Instalar dependencias
  apt:
    name:
      - python3-pip
      - python3-venv
      - git
    state: present
    update_cache: yes

- name: Instalar PostgreSQL
  apt:
    name: 
      - "postgresql-{{ postgresql_version }}"
      - "postgresql-contrib-{{ postgresql_version }}"
    state: present
    update_cache: yes

- name: Asegurar que PostgreSQL esté iniciado
  service:
    name: postgresql
    enabled: true
    state: started