- name: DEBUG - Mostrar variable postgresql_version
  debug:
    msg: "Versión de PostgreSQL: {{ postgresql_version }}"

- name: Instalar PostgreSQL y dependencias
  import_tasks: install.yml

- name: Configurar PostgreSQL
  import_tasks: config.yml

- name: Crear bases de datos
  import_tasks: databases.yml

- name: Crear usuarios
  import_tasks: users.yml