name: Terraform Deploy GCP

on:
  workflow_dispatch:
  push:
    paths:
      - 'terraform/**'
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment:
      name: Develpment

    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set environment variables
      run: |
        echo "TF_VAR_project=${{ vars.GCP_PROJECT }}" >> $GITHUB_ENV
        echo "TF_VAR_region=${{ vars.GCP_REGION }}" >> $GITHUB_ENV

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
