name: Terraform Deploy GCP

on:
  workflow_dispatch:
  push:
    paths:
      - 'terraform/**'
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment:
      name: Development

    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Verify secret is available
      run: |
        if [ -z "${{ secrets.GCP_CREDENTIALS }}" ]; then
          echo "Secret missing!"
          exit 1
        else
          echo "Secret available"
        fi

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        export_environment_variables: true

    - name: Crear terraform.tfvars
      run: |
        cat <<EOF > terraform.tfvars
        project     = "${{ vars.GCP_PROJECT }}"
        region      = "${{ vars.GCP_REGION }}"
        zone      = "${{ vars.GCP_ZONE }}"
        environment = "${{ vars.ENVIRONMENT }}"
        EOF

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check
      env:
        TF_LOG: DEBUG

    - name: Terraform Plan
      run: terraform plan
      env:
        TF_LOG: DEBUG

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
      env:
        TF_LOG: DEBUG